### ISSUE TITLE
Make the price range facet dynamic

### ISSUE THREAD

**Issue by smknstd** [meilisearch/ecommerce-demo#11]
https://github.com/meilisearch/product/discussions/117#discussioncomment-4981262

as soon as https://github.com/meilisearch/meilisearch/milestone/45 will be released ?

**Comment by Strift** [comment]
Hey @smknstd, thanks for opening an issue.

Totally agree with this one. Can't wait for Meilisearch v1.1 to release and instant-meilisearch to be updated so I can update this 😁 

It's at the very top of my list!

**Comment by smknstd** [comment]
Excellent !
